# -*- coding: utf-8 -*-
"""Lecture3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19fAuPFviabQTtqmhUKOOmJkQarc4W7pm
"""

import time

#while Loop

i = 1
while i == 1:
  print(i)
i = i+1

#For Loop
#range(start,stop,step)

#print all even numbers between 0 to 21
for i in range(0,21):
  if i % 2 == 0:
    print(i)

#print all odd numbers between 0 to 21
for i in range(0,21):
  if i % 2 == 1:
    print(i)

#String Data Type along with List
# For Loop can iterate through the Data Structures in Python
# List is the data structure in pp that is arranged in sequential structure
# Tuple is iterable but immutable
str = ['Hello',"World","Pyhton Programming"]
for i in str:
    print(i)

# Tuple is iterable but immutable
str = ('Hello',"World","Pyhton Programming")
for i in str:
    print(i)

name = "India"
print(type(name))

'''
Note:
When any function defined inside a class it is called
"Method of respective class"

'''

#Method of String
#used in NLP(natural langua processing)
print(name.capitalize()) #Camel Casing
print(name.casefold())
print(name.lower()) #lower casing
print(name.upper()) #upper casing
print(name.zfill(1))

#Method - function inside of a class- Resuable
# @ decorator static methods - used for FASTApi

name =[1,2,7,5,9,8,9]
str = ["A","k","B"]
name.reverse()
print(name)

name.sort()
print(name)
print(str.sort()) # Only Numbers can be sorted

#Enumerate function - fetches value from the given list
#
names = ['chandan','anjali','rohit','priya','sneha']
for index,name in enumerate(names):
  print(f'Index :{index},Name :{name}')



